import Head from 'next/head'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>BeeBombshell's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/beebombshell.png" type='image/x-icon' />
      </Head>

      <h1 className='p-10 text-red-500'>Hey There! 👋</h1>
    </>
  )
}