import Head from 'next/head'
import Header from '../components/Header'
import Hero from '../components/Hero'
import About from '../components/About'
import WorkExperience from '../components/WorkExperience'


export default function Home() {
  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-scroll z-0'>
      <Head>
        <title>BeeBombshell's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/beebombshell.png" type='image/x-icon' />
      </Head>

      {/* Header */}
      <Header />

      {/* Hero */}
      <section id="hero" className='snap-start'>
        <Hero />
      </section>

      {/* About Me */}
      <section id="about" className='snap-center'>
        <About />
      </section>

      {/* Experience */}
      <section className='snap-center' id='experience'>
          <WorkExperience />
      </section>

      {/* Skills */}

      {/* Projects */}

      {/* Contact Me */}
    </ div>
  )
}